### ISSUE TITLE
Archive of Discussion: Weapons

### ISSUE THREAD

**Issue by SpartanWraith** [exyleio/exyleio#53]
### Description

Discussion of what weapons should/shouldn't be added to the game was held whilst the documentation about weapons and their stats was being created. A link to the discussion is below.

https://discord.com/channels/989707899519524924/989708187194245171/999520917879275560

### Why?

Archives the discussion surrounding what weapons to add to the game, and their related stats and features. Further suggestions can still be made, however, if points that were previously discussed are brough up again, it may be ignored or dismissed. Read before you speak.

**Comment by developomp** [comment]
I have to close this issue since it's too broad and thus unsearchable.
A discussion archive should be just like a suggestion/bug report just submitted by someone else. e.g. Add rocket launcher weapon, add grappling gun, etc.
